services:
  - type: web
    name: gk-eventos
    env: docker
    plan: free
    buildCommand: 'composer install && php artisan key:generate && php artisan migrate --force'
    
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: gk-db
          property: host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromDatabase:
          name: gk-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: gk-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: gk-db
          property: password

databases:
  - name: gk-db
    plan: free
